Update openai_compatible.py
Fixing error

KeyError: 'Could not automatically map gpt4 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'